name = "Fulfillment"
author = "Ally"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d53a9c13b157c4d2dddf160e76bf06d8979401fcf9ff3c66d9bcc97246915ab"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
