name = "Fulfillment"
author = "Ally"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ecd56feba534aa213e2148c9177345971bab949af5eaf6b61eb15af0047f0cd"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
