name = "Fulfillment"
author = "Ally"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdd00c4f1db677c9f9199297ea09b27e1ee5b3371107d483511752ec3adfa3ec"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
